TRUNCATE `h5g8w9v3_GOVTEST`.`PASSENGER_ARRIVAL_DEPARTURE_INFO`;
TRUNCATE `h5g8w9v3_GOVTEST`.`PASSENGER_ADDRESS`;
TRUNCATE `h5g8w9v3_GOVTEST`.`PASSENGER_CONTACT_INFORMATION`;
TRUNCATE `h5g8w9v3_GOVTEST`.`PASSENGER_INFORMATION`;
TRUNCATE `h5g8w9v3_GOVTEST`.`PASSENGER_TRAVEL_DOCUMENTS`;
TRUNCATE `h5g8w9v3_GOVTEST`.`REGISTRATION_ID_LINKS`;
TRUNCATE `h5g8w9v3_GOVTEST`.`TRAVEL_DOCUMENTS_UPLOAD`;
TRUNCATE `h5g8w9v3_GOVTEST`.`SYSTEM_LOGS`;
TRUNCATE `h5g8w9v3_GOVTEST`.`SYSTEM_QUEUES`;


ALTER TABLE REGISTRATION_ID_LINKS AUTO_INCREMENT=1000;